version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      # Mount project code for live edits
      - ./:/var/www/html:cached
      # Keep vendor directory from image in a named volume so host mount doesn't hide it
      - vendor-data:/var/www/html/vendor
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=liga
      - DB_USERNAME=liga
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: liga
      MYSQL_USER: liga
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  db-data:
  vendor-data:
